# Generated by Django 3.0.2 on 2020-01-07 16:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0002_personalnote'),
    ]

    operations = [
        migrations.AddField(
            model_name='note',
            name='subtitle',
            field=models.CharField(default="If you don't know what to say", max_length=200),
        ),
    ]
